### ISSUE TITLE
Plain text in php/js/mustache files

### ISSUE THREAD

**Issue by volodymyrdovhan** [deandradejatwit/stoodle#30]
Hello,

found plain text in different files: php/js/mustache. All text should be defined in language files and used with String API: 
https://docs.moodle.org/dev/String_API

![image](https://github.com/user-attachments/assets/940e46ae-7b35-4887-9464-895aec753f70)

![image](https://github.com/user-attachments/assets/65ce462b-cc0a-46ae-a8d0-afbac9bde12f)

![image](https://github.com/user-attachments/assets/ff3f30de-ba03-44fe-8fb6-802ebcb6d5c5)

**Comment by kongshij** [comment]
Fixed. Thank you for the feedback. Closing issue.
