### ISSUE TITLE
Html code in php files and wrong html output

### ISSUE THREAD

**Issue by volodymyrdovhan** [deandradejatwit/stoodle#31]
Hello,

found mixed html code in php files with wrong HTML page structure. 
Moodle Output API is responsible for HTML page skeleton generation, don't need to output <HTML>, <body>, etc tags.
All HTML code should be moved to mustache templates.

![image](https://github.com/user-attachments/assets/ae9efa88-9f94-4fcd-a8d6-b597228e201e)

**Comment by kongshij** [comment]
Fixed, thank you for the feedback. Closing issue.
