### ISSUE TITLE
CSS code in php/mustache files

### ISSUE THREAD

**Issue by volodymyrdovhan** [deandradejatwit/stoodle#32]
Hello,

I found mixed CSS styles in PHP/Mustache files. All CSS should be in stylesheet file(s), which are cached by Moodle.

Please review the documentation:
https://docs.moodle.org/dev/CSS_Coding_Style
https://moodledev.io/docs/4.4/apis/plugintypes/theme/styles

![image](https://github.com/user-attachments/assets/52ad46c2-2aad-48eb-a1db-8d2c8db9e7a4)
![image](https://github.com/user-attachments/assets/918b9233-32a3-4ffd-b6be-43ce8bb0c4d9)

In addition, all CSS selectors should be unique for the plugin and do not override other CSS rules:
https://moodledev.io/general/community/plugincontribution/checklist#css-styles
![image](https://github.com/user-attachments/assets/e3e03868-d989-41e2-986d-e8f23c8d1084)

**Comment by kongshij** [comment]
Fixed. Thank you for the feedback. Closing issue.
