### ISSUE TITLE
Incorrect usage and access to global $SESSION

### ISSUE THREAD

**Issue by volodymyrdovhan** [deandradejatwit/stoodle#33]
Hello,

I found incorrect usage and access to global $SESSION in your plugin.
The logic of using these parameters should be implemented with POST and GET requests/variables, but not SESSION usage.

![image](https://github.com/user-attachments/assets/75a2d4e3-06a9-4989-9c80-ac932f15ad0b)
![image](https://github.com/user-attachments/assets/d26d4c40-6716-424b-bd40-dd055abd8ff4)
![image](https://github.com/user-attachments/assets/4d46e946-1667-4ae1-8b31-fb5f908a86b3)
![image](https://github.com/user-attachments/assets/5d1091b9-6e5f-44f1-be45-625b55560434)

The same for global $error:
![image](https://github.com/user-attachments/assets/8ec358e2-c513-4cd0-9187-744560b55c02)

**Comment by JhonDean** [comment]
Fixed. Thank you for the feedback. Closing issue.
